version: "3.8"

services:
  front:
    build:
      context: .
      dockerfile: dockerfiles/front/Dockerfile
    command: sh -c "yarn install && yarn dev"
    volumes:
      - ./front:/src
      - node_modules:/usr/app/node_modules
    ports:
      - "8001:5173"
    networks:
      - back_network
      - front_network
    tty: true
    stdin_open: true
    restart: always

  back:
    build:
      context: ./back
      dockerfile: ../dockerfiles/back/Dockerfile
    working_dir: /usr/src/back/
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "8000:3000"
    volumes:
      - ./back:/usr/src/back
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - back_network
    restart: always

  db:
    image: postgres:14.6-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    networks:
      - back_network
    restart: always
  
  # nginx:
  #   build:
  #     context: ./nginx
  #     dockerfile: ../dockerfiles/nginx/Dockerfile
  #   expose:
  #     - 8002
  #   depends_on:
  #     - back
  #     - front
  #   networks:
  #     - front_network
  #     - back_network
  #   restart: always

  # https-portal:
  #   image: steveltn/https-portal:1
  #   ports:
  #     - 80:80
  #     - 443:443
  #   depends_on:
  #     - nginx
  #   networks:
  #     - front_network
  #     - back_network
  #   environment:
  #     DOMAINS: 'localhost -> http://nginx:8002'
  #     STAGE: 'local'
  #   restart: always

  pgadmin4:
    image: dpage/pgadmin4
    ports:
        - 8880:80
    volumes:
        - pgadmin4_data:/var/lib/pgadmin
    environment:
        PGADMIN_DEFAULT_EMAIL: root@gmail.com
        PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - db
    networks:
      - back_network

volumes:
  db_data:
  pgadmin4_data:
  node_modules:

networks:
  front_network:
    external: false
  back_network:
    external: false
